# Pandas in Python

In [17]:
# Def: Pandas is a open source library designed to perform data manipulation and Analysis.

# Pandas is built over the Numpy.

# Pandas datastructure like DataFrame will store the data at backend using Numpy 2D array.

# Important list of operations in Pandas
1. Installation of Pandas
2. Data structure (Series, Data Frame)
3. Input and Output data in pandas (CSV, EXCEL, SQL, JSON)
4. Understanding the dataset (head, tail, dtype..)
5. Data filtering and indexing (loc, iloc, where()..)
6. Handling of Null values (NaN, NULL)
7. Remove duplicates
8. Handling of inconsistency inside the data (RAJ, Raj, raj, RAj, Mr.Raj, Mr. Raj)
9. Data transformation using apply(), map()
10. Aggregation and Grouping
11. Time Series operation
12. Data Visualization

# 1. Installation of Pandas

In [2]:
# pip install pandas
# conda install pandas

# this command will install the NEW version of pandas but other dependent libraries still support 
# old version of panda so they will create the issue

import pandas as pd

In [3]:
pd.__version__

'2.2.3'

# 2. Data structure (Series, Data Frame)

In [4]:
# Series : 1D array

ser1 = pd.Series()

print(ser1)

Series([], dtype: object)

In [5]:
# create a series from list

Salary = [50, 25, 75, 15, 32, 90, 100, 200, 300, 500]

Salary_series = pd.Series(Salary)
print(Salary_series)

0     50
1     25
2     75
3     15
4     32
5     90
6    100
7    200
8    300
9    500
dtype: int64

In [22]:
type(Salary_series)

pandas.core.series.Series

In [23]:
# Series() don't support the Negative indexing
# Salary_series[-1]

KeyError: -1

In [6]:
# Series from the Tuple

X_names = ("Chinki", "Minki", "Tinki", "Pinki")

Salary_series = pd.Series(X_names, index = ['A', 'B', 'C', 'D'])
print(Salary_series)

A    Chinki
B     Minki
C     Tinki
D     Pinki
dtype: object

In [25]:
Salary_series['B']

'Minki'

## Data frame in pandas

In [7]:
# dataframe is 2D array / Tables

df1 = pd.DataFrame()

print(df1)

Empty DataFrame
Columns: []
Index: []

In [8]:
# creating df from list
fruits = ["Arati Pandu", "Mamidi Pandu", "Kamala Pandu", "Panasa pandu"]

df1 = pd.DataFrame(fruits, columns = ['Pandu Peru'])

print(df1)

     Pandu Peru
0   Arati Pandu
1  Mamidi Pandu
2  Kamala Pandu
3  Panasa pandu

In [28]:
type(df1)

pandas.core.frame.DataFrame

In [10]:
# list of list into dataframe
fruits = [["Arati Pandu",70], ["Mamidi Pandu",800], ["Kamala Pandu", 300], ["Panasa pandu",120]]

df1 = pd.DataFrame(fruits, columns = ["Pandu Peru", "Darah"], index = ['A', 'B', 'C', 'D'])
print(df1)

     Pandu Peru  Darah
A   Arati Pandu     70
B  Mamidi Pandu    800
C  Kamala Pandu    300
D  Panasa pandu    120

In [11]:
# tuple of tuple into dataframe
fruits = {("Arati Pandu",70), ("Mamidi Pandu",800), ("Kamala Pandu", 300), ("Panasa pandu",120)}

df1 = pd.DataFrame(fruits, columns = ["Pandu Peru", "Darah"])
print(df1)

     Pandu Peru  Darah
0  Kamala Pandu    300
1  Panasa pandu    120
2   Arati Pandu     70
3  Mamidi Pandu    800

In [12]:
# Creating a Dataframe from the Dictionary

South_Hero = {
    "Hero Name" : ["NTR", "Prabhas", "Anudeep", "BoB", "PK", "Kirti Suresh"],
    "Movie Fee" : [200, 1000, 0, 500, 50, 100]    
}

df1 = pd.DataFrame(South_Hero)
print(df1)

      Hero Name  Movie Fee
0           NTR        200
1       Prabhas       1000
2       Anudeep          0
3           BoB        500
4            PK         50
5  Kirti Suresh        100

# 3. Input and Output data in pandas (CSV, EXCEL, SQL, JSON)

In [13]:
# Load the CSV file to DataFrame

import os
os.getcwd()

'C:\\Users\\Prikshit_Ishi\\Complete_Data_Science\\Pandas'

In [33]:
df_csv = pd.read_csv("CSV_data.csv")

In [34]:
df_csv

       Name   Age         Profession  Salary                    Favorite Quote
0      John  25.0  Software Engineer   80000            Keep calm and code on!
1     Alice   NaN             Doctor  120000           Trust me, I'm a doctor!
2     Rocky   NaN              Boxer   50000                 Eye of the tiger!
3  Sherlock  40.0          Detective  150000  It's elementary, my dear Watson.
4  Mr. Bean  50.0           Comedian   10000                   Why so serious?
5  Mr. Bean  50.0           Comedian   10000                   Why so serious?

In [15]:
# Load the Excel file as Data Frame
df = pd.read_excel("Excel_data.xlsx")
type(df)

pandas.core.frame.DataFrame

In [36]:
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [37]:
import pandas as pd

In [39]:
# Store the dataframe (df) into CSV & Excel file
df.to_excel("Da19_Excel_file1234.xlsx", index = False)

In [40]:
df.to_csv("Da19_csv_file.csv", index = False)

# Load and Store SQL based .db file

In [41]:
import sqlite3

In [46]:
conn = sqlite3.connect("DA19_database.db")

In [43]:
df.to_sql("mywish_table", conn, if_exists = "replace")

500

In [44]:
df1 = pd.read_sql("Select * FROM mywish_table", conn)

In [45]:
df1

,index,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,0,1,olivia,23.0,Teacher,184518,0
1,1,2,sophia,20.0,Boxer,119572,2
2,2,3,jake,38.0,Scientist,174897,1
3,3,4,Rocky,56.0,Chef,117920,2
4,4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...,...
495,495,496,John,45.0,Boxer,137929,0
496,496,497,Sherlock,46.0,Boxer,39870,6
497,497,498,Sherlock,47.0,Detective,165951,5
498,498,499,Olivia,55.0,Comedian,192618,5
499,499,500,Sherlock,59.0,Software Engineer,194886,28

# Load the data from JSON

In [48]:
# JSON format of file is used to send & Receive the data from the SERVER.

df2 = pd.read_json("json_data.json")
df2

,order_id,customer_name,food_item,delivery_boy,rating,delivery_time_min
0,101,Ramu,Idli Burger,Speed Shankar,5,15
1,102,Priya,Dosa Pizza,Late Laxman,2,60
2,103,Dinesh,Paneer Sambar,Turbo Thambi,4,25
3,104,Lachu,Mango Maggi,Round Robin,1,90
4,105,Meena,Coconut Coffee,Careless Kannan,3,40

In [52]:
df2.to_json("food_data.json")

# 4. Understanding the dataset (head, tail, dtype..)

In [16]:
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [17]:
df.shape

(500, 6)

In [18]:
df.head(10)

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1
5   4      Rocky  56.0         Chef  117920                        3
6   4      Rocky  56.0         Chef  117920                       11
7   4      Rocky  56.0         Chef  117920                        2
8   4      Rocky  56.0         Chef  117920                        2
9   4      Rocky  56.0         Chef  117920                        3

In [19]:
df.tail(10)

      ID      Name   Age         Profession  salary  Marriage_proposal_count
490  491      John  57.0              Pilot  154180                        0
491  492      Emma  34.0             Artist  145412                        1
492  493      John  55.0             Artist   57720                        2
493  494    Sophia  39.0             Doctor  174500                        0
494  495     Rocky  27.0             Doctor   46975                        0
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

In [20]:
df.head()

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1

In [21]:
df.tail()

      ID      Name   Age         Profession  salary  Marriage_proposal_count
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

In [22]:
df.Name

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [23]:
df.Profession

0                Teacher
1                  Boxer
2              Scientist
3                   Chef
4                   Chef
             ...
495                Boxer
496                Boxer
497            Detective
498             Comedian
499    Software Engineer
Name: Profession, Length: 500, dtype: object

In [24]:
df[['Name', 'Profession']]

          Name         Profession
0       olivia            Teacher
1    sophia                 Boxer
2         jake          Scientist
3        Rocky               Chef
4        Rocky               Chef
..         ...                ...
495       John              Boxer
496   Sherlock              Boxer
497   Sherlock          Detective
498     Olivia           Comedian
499   Sherlock  Software Engineer

[500 rows x 2 columns]

In [25]:
df['Name']

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

## Renaming of column

In [26]:
df_rename = df.rename(columns = {'Profession' : 'Vrutti'})
df_rename

      ID       Name   Age             Vrutti  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [27]:
df_rename = df_rename.rename(columns = {'Profession' : 'Vrutti'})

In [28]:
df_rename.columns

Index(['ID', 'Name', 'Age', 'Vrutti', 'salary', 'Marriage_proposal_count'], dtype='object')

# Creating NEW column in dataframe

In [29]:
df['rank'] = df['salary'].rank()

In [30]:
df['Bonus'] = 100

In [31]:
df['Bonus'] = 100000

In [32]:
df.sort_values('rank')

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank,Bonus
213,214,Sherlock,21.0,Chef,30164,2,1.0,100000
90,91,Rocky,43.0,Software Engineer,30407,10,2.0,100000
398,399,Rocky,25.0,Scientist,30659,5,3.0,100000
329,330,Sherlock,40.0,Scientist,30905,0,4.0,100000
284,285,Jake,46.0,Detective,30971,1,5.0,100000
...,...,...,...,...,...,...,...,...
474,475,Sophia,30.0,Doctor,198653,1,496.0,100000
167,168,Mr. Bean,44.0,Comedian,198847,14,497.0,100000
132,133,Rocky,31.0,Doctor,198978,8,498.0,100000
65,66,Emma,57.0,Pilot,199317,1,499.0,100000
436,437,Sherlock,52.0,Boxer,199529,3,500.0,100000

In [33]:
# Deleting the column

df = df.drop(index = 2, axis = 0)  # axis = 1 means we are droping column

In [34]:
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank,Bonus
0,1,olivia,23.0,Teacher,184518,0,462.0,100000
1,2,sophia,20.0,Boxer,119572,2,267.0,100000
3,4,Rocky,56.0,Chef,117920,2,251.0,100000
4,4,Rocky,56.0,Chef,117920,1,251.0,100000
5,4,Rocky,56.0,Chef,117920,3,251.0,100000
...,...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0,320.0,100000
496,497,Sherlock,46.0,Boxer,39870,6,36.0,100000
497,498,Sherlock,47.0,Detective,165951,5,395.0,100000
498,499,Olivia,55.0,Comedian,192618,5,480.0,100000
499,500,Sherlock,59.0,Software Engineer,194886,28,487.0,100000

# Updating a specific value in dataframe

In [35]:
df.Name = df.Name.replace('olivia', 'Prabhas')
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank,Bonus
0,1,Prabhas,23.0,Teacher,184518,0,462.0,100000
1,2,sophia,20.0,Boxer,119572,2,267.0,100000
3,4,Rocky,56.0,Chef,117920,2,251.0,100000
4,4,Rocky,56.0,Chef,117920,1,251.0,100000
5,4,Rocky,56.0,Chef,117920,3,251.0,100000
...,...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0,320.0,100000
496,497,Sherlock,46.0,Boxer,39870,6,36.0,100000
497,498,Sherlock,47.0,Detective,165951,5,395.0,100000
498,499,Olivia,55.0,Comedian,192618,5,480.0,100000
499,500,Sherlock,59.0,Software Engineer,194886,28,487.0,100000

In [36]:
df.Name = df.Name.replace({'Prabhas' : 'Allu', 'Rocky':'Rakesh'})
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank,Bonus
0,1,Allu,23.0,Teacher,184518,0,462.0,100000
1,2,sophia,20.0,Boxer,119572,2,267.0,100000
3,4,Rakesh,56.0,Chef,117920,2,251.0,100000
4,4,Rakesh,56.0,Chef,117920,1,251.0,100000
5,4,Rakesh,56.0,Chef,117920,3,251.0,100000
...,...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0,320.0,100000
496,497,Sherlock,46.0,Boxer,39870,6,36.0,100000
497,498,Sherlock,47.0,Detective,165951,5,395.0,100000
498,499,Olivia,55.0,Comedian,192618,5,480.0,100000
499,500,Sherlock,59.0,Software Engineer,194886,28,487.0,100000

In [37]:
import pandas as pd

In [38]:
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [4]:
# dtype
df.dtypes

ID                           int64
Name                        object
Age                        float64
Profession                  object
salary                       int64
Marriage_proposal_count      int64
dtype: object

In [5]:
# convert data type
df['Name'] = df['Name'].astype("string")
df.dtypes

ID                                  int64
Name                       string[python]
Age                               float64
Profession                         object
salary                              int64
Marriage_proposal_count             int64
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       500 non-null    int64
 1   Name                     500 non-null    string
 2   Age                      492 non-null    float64
 3   Profession               500 non-null    object
 4   salary                   500 non-null    int64
 5   Marriage_proposal_count  500 non-null    int64
dtypes: float64(1), int64(3), object(1), string(1)
memory usage: 23.6+ KB

In [7]:
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [16]:
# Query: Print all the Unique type of profession
df['Profession'].unique()

array(['Teacher', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [10]:
df['Name'].unique()

<StringArray>
[   'olivia', 'sophia   ',      'jake',     'Rocky',      'Jake',    'Olivia',
      'John',  'Sherlock',     'Alice',  'Mr. Bean',    'Sophia',      'Liam',
      'Emma']
Length: 13, dtype: string

In [19]:
df.Name.nunique()

13

In [20]:
# value_counts() : count the number of records for unique values
df.Profession.value_counts()

Profession
Chef                 58
Scientist            54
Pilot                53
      Boxer          53
Comedian             52
Software Engineer    51
Doctor               48
Teacher              45
Detective            45
Artist               41
Name: count, dtype: int64

In [26]:
# Statistical summary : describe()
df.describe(include = 'all')

,ID,Name,Age,Profession,salary,Marriage_proposal_count
count,500.000000,500,492.000000,500,500.000000,500.00000
unique,NaN,13,NaN,10,NaN,NaN
top,NaN,Sherlock,NaN,Chef,NaN,NaN
freq,NaN,61,NaN,58,NaN,NaN
mean,250.458000,NaN,40.810976,NaN,115602.828000,4.02600
std,144.552978,NaN,11.790553,NaN,49404.366846,5.25362
min,1.000000,NaN,20.000000,NaN,30164.000000,0.00000
25%,125.750000,NaN,31.000000,NaN,74964.750000,1.00000
50%,250.500000,NaN,40.500000,NaN,117920.000000,3.00000
75%,375.250000,NaN,51.000000,NaN,160579.500000,5.00000
max,500.000000,NaN,60.000000,NaN,199529.000000,40.00000

In [24]:
# percentage & percentile

In [25]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

In [27]:
df.ID.unique()

array([  1,   2,   3,   4,  11,  12,  13,  14,  15,  16,  17,  18,  19,
        20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
        33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
        46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,
        59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
        72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
        98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
       111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
       124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136,
       137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
       150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
       163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
       176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
       189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201,
       202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214,
       215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227,
       228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240,
       241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253,
       254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266,
       267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279,
       280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292,
       293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305,
       306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318,
       319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331,
       332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344,
       345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357,
       358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370,
       371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383,
       384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396,
       397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409,
       410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422,
       423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435,
       436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448,
       449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461,
       462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474,
       475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487,
       488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500])

# 5. Data filtering and indexing (loc, iloc, where()..)

In [29]:
# Query: filter all the records where salary > 100000

df[df.salary > 100000]

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
493  494     Sophia  39.0             Doctor  174500                        0
495  496       John  45.0              Boxer  137929                        0
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[304 rows x 6 columns]

In [32]:
# Query: filter all the records where salary > 100000 | salary < 50000

df[(df.salary > 100000) | (df.salary < 50000) ]

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[368 rows x 6 columns]

In [36]:
# Query: Find the person record who is getting maximum salary

df[df.salary == df.salary.max()]

      ID      Name   Age   Profession  salary  Marriage_proposal_count
436  437  Sherlock  52.0        Boxer  199529                        3

In [37]:
df.salary.max()

199529

In [38]:
# Query: find the person record who is getting maximum proposal.

df[df.Marriage_proposal_count == df.Marriage_proposal_count.max()]

      ID   Name   Age Profession  salary  Marriage_proposal_count
399  400  Rocky  52.0   Comedian   69267                       40

In [47]:
# Query : Find the person PROFESSION who is getting minimum salary
df.Profession[df.salary == df.salary.min()]

213    Chef
Name: Profession, dtype: object

In [49]:
df[['Profession','salary']][df.salary == df.salary.min()]

    Profession  salary
213       Chef   30164

# loc & iloc : helps to print a range of records

In [50]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

In [52]:
df.loc[1:4, "ID" : "Age"]

   ID       Name   Age
1   2  sophia     20.0
2   3       jake  38.0
3   4      Rocky  56.0
4   4      Rocky  56.0

In [54]:
# iloc support the negative indexing but dataframe "directly" don't support the negative indexing
df.iloc[-8:-3, 0:3]

      ID      Name   Age
492  493      John  55.0
493  494    Sophia  39.0
494  495     Rocky  27.0
495  496      John  45.0
496  497  Sherlock  46.0

In [1]:
# Interview Question: What is the difference between loc & iloc?

In [39]:
import os
os.getcwd()

'C:\\Users\\Prikshit_Ishi\\Complete_Data_Science\\Pandas'

In [40]:
import pandas as pd

In [41]:
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

## sorting rows

In [44]:
df.sort_values('salary').head(20)

      ID      Name   Age         Profession  salary  Marriage_proposal_count
213  214  Sherlock  21.0               Chef   30164                        2
90    91     Rocky  43.0  Software Engineer   30407                       10
398  399     Rocky  25.0          Scientist   30659                        5
329  330  Sherlock  40.0          Scientist   30905                        0
284  285      Jake  46.0          Detective   30971                        1
383  384      John  23.0              Boxer   30976                        3
153  154     Alice  56.0              Boxer   31088                       11
358  359      Liam  35.0              Pilot   31129                        4
229  230      John  35.0            Teacher   31162                        1
159  160      Emma  60.0             Doctor   31209                        3
462  463    Sophia  32.0          Detective   31851                        3
197  198      Liam  59.0             Doctor   31945                        5
39    40    Olivia  60.0  Software Engineer   32286                        1
136  137    Olivia  23.0           Comedian   32354                        1
154  155     Alice  25.0             Artist   32961                        5
166  167      Emma  24.0  Software Engineer   33049                        3
148  149    Sophia  32.0             Artist   33603                        5
349  350  Mr. Bean  58.0            Teacher   34337                       37
120  121  Mr. Bean  43.0               Chef   34630                        2
152  153     Alice  57.0            Teacher   34825                        0

In [48]:
# sort in decending order
df.sort_values('salary', ascending = False).head(20)

      ID      Name   Age         Profession  salary  Marriage_proposal_count
436  437  Sherlock  52.0              Boxer  199529                        3
65    66      Emma  57.0              Pilot  199317                        1
132  133     Rocky  31.0             Doctor  198978                        8
167  168  Mr. Bean  44.0           Comedian  198847                       14
474  475    Sophia  30.0             Doctor  198653                        1
439  440      Jake  38.0  Software Engineer  198285                        3
117  118    Olivia  25.0          Scientist  198095                        0
214  215      Liam  22.0             Artist  197685                        2
485  486  Mr. Bean  59.0              Pilot  196562                        3
137  138      Emma  40.0          Scientist  196516                        5
178  179     Alice  38.0               Chef  196494                        4
306  307     Rocky  30.0           Comedian  196351                        0
25    26    Olivia  53.0          Detective  194971                        3
499  500  Sherlock  59.0  Software Engineer  194886                       28
203  204      Emma  38.0  Software Engineer  194615                        2
400  401    Olivia  50.0             Doctor  194401                        2
75    76     Alice  60.0             Doctor  193629                        3
246  247      Liam  32.0             Doctor  193498                        0
486  487  Mr. Bean  23.0             Doctor  193209                        2
236  237  Mr. Bean  46.0          Detective  193168                        0

In [50]:
# sort based upon string column
df.sort_values("Name", ascending = False)

      ID       Name   Age   Profession  salary  Marriage_proposal_count
1      2  sophia     20.0        Boxer  119572                        2
0      1     olivia  23.0      Teacher  184518                        0
2      3       jake  38.0    Scientist  174897                        1
43    44     Sophia  51.0      Teacher  172273                        2
405  406     Sophia  29.0       Artist   67411                        8
..   ...        ...   ...          ...     ...                      ...
152  153      Alice  57.0      Teacher   34825                        0
416  417      Alice  33.0      Teacher   94768                        4
153  154      Alice  56.0        Boxer   31088                       11
154  155      Alice  25.0       Artist   32961                        5
296  297      Alice  22.0       Artist  180368                        3

[500 rows x 6 columns]

In [52]:
df.sort_index()

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [56]:
# making column as a index of dataframe
df = df.set_index('ID')

In [58]:
df = df.reset_index()
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

# 6. Handling of Null values (NaN, NULL)

In [60]:
# null value : empty

# finding the null values in the dataframe

df.isnull().sum()

ID                         0
Name                       0
Age                        8
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [62]:
# print those records which have null values


df['Age'].isnull().sum()

np.int64(8)

In [64]:
df[df['Age'].isnull()]

    ID      Name  Age         Profession  salary  Marriage_proposal_count
10  11     Rocky  NaN             Doctor   75543                        5
11  12      Jake  NaN             Artist  174780                        5
45  46      Liam  NaN             Doctor   84583                        0
46  47  Mr. Bean  NaN             Artist  190559                        5
71  72      Emma  NaN              Pilot   49986                        3
72  73    Sophia  NaN             Artist   86741                        1
73  74     Rocky  NaN  Software Engineer  159260                        0
74  75  Sherlock  NaN          Detective  165463                        0

In [65]:
# delete the null records
df1 = df.copy()

In [67]:
df1 = df1.dropna()

In [68]:
df1.shape

(492, 6)

In [69]:
df1.isnull().sum()

ID                         0
Name                       0
Age                        0
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [70]:
# deleting the column itself

df2 = df.copy()
df2 = df2.dropna(axis = 1)

In [71]:
df2

      ID       Name         Profession  salary  Marriage_proposal_count
0      1     olivia            Teacher  184518                        0
1      2  sophia                 Boxer  119572                        2
2      3       jake          Scientist  174897                        1
3      4      Rocky               Chef  117920                        2
4      4      Rocky               Chef  117920                        1
..   ...        ...                ...     ...                      ...
495  496       John              Boxer  137929                        0
496  497   Sherlock              Boxer   39870                        6
497  498   Sherlock          Detective  165951                        5
498  499     Olivia           Comedian  192618                        5
499  500   Sherlock  Software Engineer  194886                       28

[500 rows x 5 columns]

In [79]:
# filling NULL value with some other value
df3 = df.copy()

df3['Age'] = df3.Age.fillna(16)
df3.isnull().sum()

ID                         0
Name                       0
Age                        0
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

In [80]:
df3

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [82]:
df3['Age'].unique()

array([23., 20., 38., 56., 16., 22., 46., 40., 30., 53., 25., 41., 42.,
       60., 48., 55., 21., 27., 45., 44., 57., 32., 52., 39., 26., 51.,
       59., 34., 47., 36., 37., 49., 33., 28., 50., 58., 31., 43., 29.,
       54., 24., 35.])

# 7. Remove duplicates

In [84]:
# show the duplicate records

df.duplicated().sum()

np.int64(3)

In [85]:
df[df.duplicated()]

   ID   Name   Age Profession  salary  Marriage_proposal_count
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

In [86]:
df[df.duplicated(keep = False)]

   ID   Name   Age Profession  salary  Marriage_proposal_count
3   4  Rocky  56.0       Chef  117920                        2
5   4  Rocky  56.0       Chef  117920                        3
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

In [87]:
#  deleting the duplicate records
df4 = df.copy()

df4 = df4.drop_duplicates()

In [88]:
df4.duplicated().sum()

np.int64(0)

In [89]:
df4.shape

(497, 6)

# 8. Handling of inconsistency inside the data

In [90]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

In [91]:
# making first character as captical in column names
df.columns = df.columns.str.title()

In [92]:
df.columns

Index(['Id', 'Name', 'Age', 'Profession', 'Salary', 'Marriage_Proposal_Count'], dtype='object')

In [93]:
df.Name.unique()

array(['olivia', 'sophia   ', 'jake', 'Rocky', 'Jake', 'Olivia', 'John',
       'Sherlock', 'Alice', 'Mr. Bean', 'Sophia', 'Liam', 'Emma'],
      dtype=object)

In [95]:
df.Name = df.Name.str.strip()

In [96]:
df.Name.unique()

array(['olivia', 'sophia', 'jake', 'Rocky', 'Jake', 'Olivia', 'John',
       'Sherlock', 'Alice', 'Mr. Bean', 'Sophia', 'Liam', 'Emma'],
      dtype=object)

In [97]:
df.Profession.unique()

array(['Teacher', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [98]:
df.Profession = df.Profession.str.strip()

In [99]:
df.Profession.unique()

array(['Teacher', 'Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)