# Pandas in Python

In [17]:
# Def: Pandas is a open source library designed to perform data manipulation and Analysis.

# Pandas is built over the Numpy.

# Pandas datastructure like DataFrame will store the data at backend using Numpy 2D array.

# Important list of operations in Pandas
1. Installation of Pandas
2. Data structure (Series, Data Frame)
3. Input and Output data in pandas (CSV, EXCEL, SQL, JSON)
4. Understanding the dataset (head, tail, dtype..)
5. Data filtering and indexing (loc, iloc, where()..)
6. Handling of Null values (NaN, NULL)
7. Remove duplicates
8. Handling of inconsistency inside the data (RAJ, Raj, raj, RAj, Mr.Raj, Mr. Raj)
9. Data transformation using apply(), map()
10. Aggregation and Grouping
11. Time Series operation
12. Data Visualization

# 1. Installation of Pandas

In [18]:
# pip install pandas
# conda install pandas

# this command will install the NEW version of pandas but other dependent libraries still support 
# old version of panda so they will create the issue

import pandas as pd

In [19]:
pd.__version__

'2.2.3'

# 2. Data structure (Series, Data Frame)

In [20]:
# Series : 1D array

ser1 = pd.Series()

print(ser1)

Series([], dtype: object)

In [21]:
# create a series from list

Salary = [50, 25, 75, 15, 32, 90, 100, 200, 300, 500]

Salary_series = pd.Series(Salary)
print(Salary_series)

0     50
1     25
2     75
3     15
4     32
5     90
6    100
7    200
8    300
9    500
dtype: int64

In [22]:
type(Salary_series)

pandas.core.series.Series

In [23]:
# Series() don't support the Negative indexing
# Salary_series[-1]

KeyError: -1

In [24]:
# Series from the Tuple

X_names = ("Chinki", "Minki", "Tinki", "Pinki")

Salary_series = pd.Series(X_names, index = ['A', 'B', 'C', 'D'])
print(Salary_series)

A    Chinki
B     Minki
C     Tinki
D     Pinki
dtype: object

In [25]:
Salary_series['B']

'Minki'

## Data frame in pandas

In [26]:
# dataframe is 2D array / Tables

df1 = pd.DataFrame()

print(df1)

Empty DataFrame
Columns: []
Index: []

In [27]:
# creating df from list
fruits = ["Arati Pandu", "Mamidi Pandu", "Kamala Pandu", "Panasa pandu"]

df1 = pd.DataFrame(fruits, columns = ['Pandu Peru'])

print(df1)

     Pandu Peru
0   Arati Pandu
1  Mamidi Pandu
2  Kamala Pandu
3  Panasa pandu

In [28]:
type(df1)

pandas.core.frame.DataFrame

In [29]:
# list of list into dataframe
fruits = [["Arati Pandu",70], ["Mamidi Pandu",800], ["Kamala Pandu", 300], ["Panasa pandu",120]]

df1 = pd.DataFrame(fruits, columns = ["Pandu Peru", "Darah"])
print(df1)

     Pandu Peru  Darah
0   Arati Pandu     70
1  Mamidi Pandu    800
2  Kamala Pandu    300
3  Panasa pandu    120

In [30]:
# tuple of tuple into dataframe
fruits = {("Arati Pandu",70), ("Mamidi Pandu",800), ("Kamala Pandu", 300), ("Panasa pandu",120)}

df1 = pd.DataFrame(fruits, columns = ["Pandu Peru", "Darah"])
print(df1)

     Pandu Peru  Darah
0   Arati Pandu     70
1  Panasa pandu    120
2  Kamala Pandu    300
3  Mamidi Pandu    800

In [31]:
# Creating a Dataframe from the Dictionary

South_Hero = {
    "Hero Name" : ["NTR", "Prabhas", "Anudeep", "BoB", "PK", "Kirti Suresh"],
    "Movie Fee" : [200, 1000, 0, 500, 50, 100]    
}

df1 = pd.DataFrame(South_Hero)
print(df1)

      Hero Name  Movie Fee
0           NTR        200
1       Prabhas       1000
2       Anudeep          0
3           BoB        500
4            PK         50
5  Kirti Suresh        100

# 3. Input and Output data in pandas (CSV, EXCEL, SQL, JSON)

In [32]:
# Load the CSV file to DataFrame

import os
os.getcwd()

'C:\\Users\\Prikshit_Ishi\\Complete_Data_Science\\Pandas'

In [33]:
df_csv = pd.read_csv("CSV_data.csv")

In [34]:
df_csv

       Name   Age         Profession  Salary                    Favorite Quote
0      John  25.0  Software Engineer   80000            Keep calm and code on!
1     Alice   NaN             Doctor  120000           Trust me, I'm a doctor!
2     Rocky   NaN              Boxer   50000                 Eye of the tiger!
3  Sherlock  40.0          Detective  150000  It's elementary, my dear Watson.
4  Mr. Bean  50.0           Comedian   10000                   Why so serious?
5  Mr. Bean  50.0           Comedian   10000                   Why so serious?

In [35]:
# Load the Excel file as Data Frame
df = pd.read_excel("Excel_data.xlsx")
type(df)

pandas.core.frame.DataFrame

In [36]:
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [37]:
import pandas as pd

In [39]:
# Store the dataframe (df) into CSV & Excel file
df.to_excel("Da19_Excel_file1234.xlsx", index = False)

In [40]:
df.to_csv("Da19_csv_file.csv", index = False)

# Load and Store SQL based .db file

In [41]:
import sqlite3

In [46]:
conn = sqlite3.connect("DA19_database.db")

In [43]:
df.to_sql("mywish_table", conn, if_exists = "replace")

500

In [44]:
df1 = pd.read_sql("Select * FROM mywish_table", conn)

In [45]:
df1

,index,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,0,1,olivia,23.0,Teacher,184518,0
1,1,2,sophia,20.0,Boxer,119572,2
2,2,3,jake,38.0,Scientist,174897,1
3,3,4,Rocky,56.0,Chef,117920,2
4,4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...,...
495,495,496,John,45.0,Boxer,137929,0
496,496,497,Sherlock,46.0,Boxer,39870,6
497,497,498,Sherlock,47.0,Detective,165951,5
498,498,499,Olivia,55.0,Comedian,192618,5
499,499,500,Sherlock,59.0,Software Engineer,194886,28

# Load the data from JSON

In [48]:
# JSON format of file is used to send & Receive the data from the SERVER.

df2 = pd.read_json("json_data.json")
df2

,order_id,customer_name,food_item,delivery_boy,rating,delivery_time_min
0,101,Ramu,Idli Burger,Speed Shankar,5,15
1,102,Priya,Dosa Pizza,Late Laxman,2,60
2,103,Dinesh,Paneer Sambar,Turbo Thambi,4,25
3,104,Lachu,Mango Maggi,Round Robin,1,90
4,105,Meena,Coconut Coffee,Careless Kannan,3,40

In [52]:
df2.to_json("food_data.json")

# 4. Understanding the dataset (head, tail, dtype..)

In [50]:
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [53]:
df.shape

(500, 6)

In [54]:
df.head(10)

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1
5   4      Rocky  56.0         Chef  117920                        3
6   4      Rocky  56.0         Chef  117920                       11
7   4      Rocky  56.0         Chef  117920                        2
8   4      Rocky  56.0         Chef  117920                        2
9   4      Rocky  56.0         Chef  117920                        3

In [55]:
df.tail(10)

      ID      Name   Age         Profession  salary  Marriage_proposal_count
490  491      John  57.0              Pilot  154180                        0
491  492      Emma  34.0             Artist  145412                        1
492  493      John  55.0             Artist   57720                        2
493  494    Sophia  39.0             Doctor  174500                        0
494  495     Rocky  27.0             Doctor   46975                        0
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

In [56]:
df.head()

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1

In [57]:
df.tail()

      ID      Name   Age         Profession  salary  Marriage_proposal_count
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

In [58]:
df.Name

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [59]:
df.Profession

0                Teacher
1                  Boxer
2              Scientist
3                   Chef
4                   Chef
             ...
495                Boxer
496                Boxer
497            Detective
498             Comedian
499    Software Engineer
Name: Profession, Length: 500, dtype: object

In [60]:
df[['Name', 'Profession']]

          Name         Profession
0       olivia            Teacher
1    sophia                 Boxer
2         jake          Scientist
3        Rocky               Chef
4        Rocky               Chef
..         ...                ...
495       John              Boxer
496   Sherlock              Boxer
497   Sherlock          Detective
498     Olivia           Comedian
499   Sherlock  Software Engineer

[500 rows x 2 columns]

In [63]:
df['Name']

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

## Renaming of column

In [64]:
df_rename = df.rename(columns = {'Profession' : 'Vrutti'})
df_rename

      ID       Name   Age             Vrutti  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [67]:
df_rename = df_rename.rename(columns = {'Profession' : 'Vrutti'})

In [68]:
df_rename.columns

Index(['ID', 'Peru', 'Age', 'Vrutti', 'Jitam', 'Marriage_proposal_count'], dtype='object')

# Creating NEW column in dataframe

In [69]:
df['rank'] = df['salary'].rank()

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank
0,1,olivia,23.0,Teacher,184518,0,462.0
1,2,sophia,20.0,Boxer,119572,2,267.0
2,3,jake,38.0,Scientist,174897,1,426.0
3,4,Rocky,56.0,Chef,117920,2,251.0
4,4,Rocky,56.0,Chef,117920,1,251.0
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0,320.0
496,497,Sherlock,46.0,Boxer,39870,6,36.0
497,498,Sherlock,47.0,Detective,165951,5,395.0
498,499,Olivia,55.0,Comedian,192618,5,480.0
499,500,Sherlock,59.0,Software Engineer,194886,28,487.0

In [70]:
df['Bonus'] = 100

In [72]:
df['Bonus'] = 100000

In [74]:
df.sort_values('rank')

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank,Bonus
213,214,Sherlock,21.0,Chef,30164,2,1.0,100000
90,91,Rocky,43.0,Software Engineer,30407,10,2.0,100000
398,399,Rocky,25.0,Scientist,30659,5,3.0,100000
329,330,Sherlock,40.0,Scientist,30905,0,4.0,100000
284,285,Jake,46.0,Detective,30971,1,5.0,100000
...,...,...,...,...,...,...,...,...
474,475,Sophia,30.0,Doctor,198653,1,496.0,100000
167,168,Mr. Bean,44.0,Comedian,198847,14,497.0,100000
132,133,Rocky,31.0,Doctor,198978,8,498.0,100000
65,66,Emma,57.0,Pilot,199317,1,499.0,100000
436,437,Sherlock,52.0,Boxer,199529,3,500.0,100000

In [84]:
# Deleting the column

df = df.drop(index = 2, axis = 0)  # axis = 1 means we are droping column

In [85]:
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count,Bonus
0,1,olivia,23.0,Teacher,184518,0,100000
3,4,Rocky,56.0,Chef,117920,2,100000
4,4,Rocky,56.0,Chef,117920,1,100000
5,4,Rocky,56.0,Chef,117920,3,100000
6,4,Rocky,56.0,Chef,117920,11,100000
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0,100000
496,497,Sherlock,46.0,Boxer,39870,6,100000
497,498,Sherlock,47.0,Detective,165951,5,100000
498,499,Olivia,55.0,Comedian,192618,5,100000
499,500,Sherlock,59.0,Software Engineer,194886,28,100000

# Updating a specific value in dataframe

In [86]:
df.Name = df.Name.replace('olivia', 'Prabhas')
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count,Bonus
0,1,Prabhas,23.0,Teacher,184518,0,100000
3,4,Rocky,56.0,Chef,117920,2,100000
4,4,Rocky,56.0,Chef,117920,1,100000
5,4,Rocky,56.0,Chef,117920,3,100000
6,4,Rocky,56.0,Chef,117920,11,100000
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0,100000
496,497,Sherlock,46.0,Boxer,39870,6,100000
497,498,Sherlock,47.0,Detective,165951,5,100000
498,499,Olivia,55.0,Comedian,192618,5,100000
499,500,Sherlock,59.0,Software Engineer,194886,28,100000

In [87]:
df.Name = df.Name.replace({'Prabhas' : 'Allu', 'Rocky':'Rakesh'})
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count,Bonus
0,1,Allu,23.0,Teacher,184518,0,100000
3,4,Rakesh,56.0,Chef,117920,2,100000
4,4,Rakesh,56.0,Chef,117920,1,100000
5,4,Rakesh,56.0,Chef,117920,3,100000
6,4,Rakesh,56.0,Chef,117920,11,100000
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0,100000
496,497,Sherlock,46.0,Boxer,39870,6,100000
497,498,Sherlock,47.0,Detective,165951,5,100000
498,499,Olivia,55.0,Comedian,192618,5,100000
499,500,Sherlock,59.0,Software Engineer,194886,28,100000